print ("𝔥")
print (" 𝔢")
print ("  𝔩")
print ("   𝔩")
print ("    𝔬")
print ("      ")
print ("      𝔪")
print ("       ყ")
print ("         ")
print ("         𝔱")
print ("          𝔢")
print ("           𝔞")
print ("            𝔠")
print ("             𝔥")
print ("              𝔢")
print ("               𝔯")

print ("𝔥𝔢𝔩𝔩𝔬 𝔪𝔶 𝔱𝔢𝔞𝔠𝔥𝔢𝔯")
